#!/usr/bin/env bash
# Fires before Claude Code compacts the conversation.
# Writes a deterministic skeleton to handover.md and sets a sentinel so the
# Stop hook knows to enforce completion before Claude next stops responding.
set -e

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
HANDOVER_FILE="${REPO_ROOT}/handover.md"
SENTINEL_DIR="${HOME}/.claude/llm-handoff"
SENTINEL="${SENTINEL_DIR}/completion-required"

mkdir -p "$SENTINEL_DIR"

# Collect deterministic git state
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
LAST_COMMIT=$(git log --oneline -1 2>/dev/null || echo "no commits")
GIT_STATUS=$(git status --short 2>/dev/null || echo "unable to get status")
RECENT_COMMITS=$(git log --oneline -5 2>/dev/null || echo "no commits")
WORKTREES=$(git worktree list 2>/dev/null | tail -n +2 | awk '{print $1}' || echo "N/A")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Write skeleton — LLM will complete all <!-- TODO --> sections via Stop hook enforcement
cat > "$HANDOVER_FILE" << SKELETON
---
generated: ${TIMESTAMP}
previous_llm: <!-- TODO: LLM — state your model name and version -->
tool: Claude Code
trigger: auto (PreCompact)
branch: ${BRANCH}
worktree: ${WORKTREES:-N/A}
---

# LLM Handover

> Read this file completely before taking any action. Verify repository state matches
> what is documented before starting work. If anything conflicts, investigate first.

## Quick start checklist

- [ ] Read this entire file
- [ ] Run \`git status\` — confirm it matches **Repository state** below
- [ ] Run \`git log --oneline -5\` — confirm last commit matches
- [ ] Read the files listed in **Files in play**
- [ ] Start with **Next steps item 1**

---

## Original request

<!-- TODO: LLM — reproduce verbatim or near-verbatim what the user asked for when this session started -->

## Session goal

<!-- TODO: LLM — one sentence: what we are trying to achieve -->

**Scope — in:**
<!-- TODO: LLM — what is in scope -->

**Scope — out:**
<!-- TODO: LLM — what is explicitly out of scope -->

**Constraints:**
<!-- TODO: LLM — stated or discovered constraints the next LLM must respect -->

---

## Repository state at handoff

| Field | Value |
|-------|-------|
| Branch | \`${BRANCH}\` |
| Worktree | \`${WORKTREES:-N/A}\` |
| Last commit | \`${LAST_COMMIT}\` |
| Working tree | <!-- TODO: LLM — clean or dirty --> |
| Staged | <!-- TODO: LLM — list staged files or "none" --> |
| Stashed | <!-- TODO: LLM — list stash entries or "none" --> |

**Uncommitted changes:**
\`\`\`
${GIT_STATUS:-clean working tree}
\`\`\`

**Recent commits:**
\`\`\`
${RECENT_COMMITS}
\`\`\`

---

## Progress

### Completed this session
<!-- TODO: LLM — list with file:line references where relevant -->

### In progress when handoff triggered
<!-- TODO: LLM — exactly what was being worked on (file, function, test) -->

### Not started (known remaining work)
<!-- TODO: LLM — tasks not yet touched -->

---

## Files in play

<!-- TODO: LLM — table of files relevant to current task, ordered by importance -->
| File | Why it matters |
|------|----------------|
| \`path/to/file\` | reason |

---

## Key decisions made

<!-- TODO: LLM — for each decision: what was chosen, WHY, what alternatives were rejected -->

---

## Failed approaches — do not retry

<!-- TODO: LLM — what was tried, exact error/result, root cause, alternative taken -->

---

## Blockers and open questions

<!-- TODO: LLM — unresolved issues with enough detail to act on -->

---

## Next steps

<!-- TODO: LLM — ordered list; each step names a file, what to do, how to verify -->

---

## Critical context

<!-- TODO: LLM — non-obvious things that would cause mistakes if not known -->

---

## Environment at handoff

| Item | Value |
|------|-------|
| Language / runtime | <!-- TODO: LLM --> |
| Package manager | <!-- TODO: LLM --> |
| Running services | <!-- TODO: LLM --> |
| Relevant env vars | <!-- TODO: LLM — names only --> |
| Test command | <!-- TODO: LLM --> |
| Dev server command | <!-- TODO: LLM --> |

---

## Handoff metadata

| Field | Value |
|-------|-------|
| Handoff reason | context limit (auto-compaction) |
| Previous LLM | <!-- TODO: LLM — model name and version --> |
| Tool | Claude Code |
| Generated | ${TIMESTAMP} |
| Suggested next LLM | any |

---

*Generated by [llm-handoff](https://github.com/thatsuperdev/llm-handoff)*
SKELETON

# Ensure handover.md is gitignored
GITIGNORE="${REPO_ROOT}/.gitignore"
if [ -f "$GITIGNORE" ]; then
  if ! grep -qxF "handover.md" "$GITIGNORE"; then
    echo "handover.md" >> "$GITIGNORE"
  fi
else
  echo "handover.md" > "$GITIGNORE"
fi

# Set sentinel so Stop hook enforces completion
touch "$SENTINEL"

# Output message — goes to Claude's context, instructing it to complete the handover
echo "llm-handoff: Context is approaching its limit. The git state and branch info have been written to handover.md as a starting skeleton. Before this session ends, fill in ALL the <!-- TODO --> sections in handover.md — decisions made and WHY, failed approaches with exact errors, blockers, and specific next steps. This produces a portable document the user can paste into any LLM to continue the work. Do not stop until all TODO sections are complete."
