#!/usr/bin/env bash
# Gemini CLI PreCompress hook — fires asynchronously before history compression.
# Cannot block compression. Writes a deterministic snapshot only.
# For a full handover with reasoning, invoke /llm-handoff manually before context fills.
set -e

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
HANDOVER_FILE="${REPO_ROOT}/handover.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Only write if there is no recent (< 5 min) complete handover already
if [ -f "$HANDOVER_FILE" ] && ! grep -q "<!-- TODO:" "$HANDOVER_FILE" 2>/dev/null; then
  MODIFIED_TIME=0
  if [ "$(uname)" = "Darwin" ]; then
    MODIFIED_TIME=$(stat -f %m "$HANDOVER_FILE" 2>/dev/null || echo 0)
  else
    MODIFIED_TIME=$(stat -c %Y "$HANDOVER_FILE" 2>/dev/null || echo 0)
  fi
  NOW=$(date +%s)
  AGE=$(( NOW - MODIFIED_TIME ))
  if [ "$AGE" -lt 300 ]; then
    exit 0
  fi
fi

BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
LAST_COMMIT=$(git log --oneline -1 2>/dev/null || echo "no commits")
GIT_STATUS=$(git status --short 2>/dev/null || echo "unable to get status")
RECENT_COMMITS=$(git log --oneline -5 2>/dev/null || echo "no commits")

cat > "$HANDOVER_FILE" << SNAPSHOT
---
generated: ${TIMESTAMP}
previous_llm: gemini (version unknown — check session context)
tool: Gemini CLI
trigger: auto (PreCompress — snapshot only)
branch: ${BRANCH}
---

# LLM Handover — Snapshot

> This handover was written automatically by the PreCompress hook in Gemini CLI.
> It contains ONLY deterministic state (git data). The reasoning sections (decisions,
> next steps, failed approaches) are NOT complete because PreCompress is asynchronous
> and fires too late to ask the model to fill them in.
>
> For a full handover, invoke /llm-handoff or "llm-handoff" manually BEFORE
> your context gets full.

## Repository state at snapshot

| Field | Value |
|-------|-------|
| Branch | \`${BRANCH}\` |
| Last commit | \`${LAST_COMMIT}\` |
| Generated | \`${TIMESTAMP}\` |

**Uncommitted changes:**
\`\`\`
${GIT_STATUS:-clean working tree}
\`\`\`

**Recent commits:**
\`\`\`
${RECENT_COMMITS}
\`\`\`

---

## Missing sections (requires manual /llm-handoff for full handover)

- Original request
- Session goal
- Progress
- Files in play
- Key decisions and WHY
- Failed approaches
- Blockers
- Next steps
- Critical context
- Environment

---

*Generated by [llm-handoff](https://github.com/thatsuperdev/llm-handoff) — Gemini CLI PreCompress hook*
SNAPSHOT

# Ensure gitignored
GITIGNORE="${REPO_ROOT}/.gitignore"
if [ -f "$GITIGNORE" ]; then
  grep -qxF "handover.md" "$GITIGNORE" || echo "handover.md" >> "$GITIGNORE"
else
  echo "handover.md" > "$GITIGNORE"
fi
